
stages:
  - code-quality
  - heroku-publish
default:
  interruptible: true
  retry:
    max: 2
    when:
      - unknown_failure
      - script_failure
      - api_failure
      - stuck_or_timeout_failure
      - runner_system_failure
      - job_execution_timeout
      - scheduler_failure
      - data_integrity_failure
  tags:
    - docker

include:
  - local: "/gitlab-ci/includes.yml"

fragment-version-check:
  extends: .fragment-version-check-template
workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE != "scheduled"
      when: never
    - if: $CI_COMMIT_BRANCH
      when: always

gitleaks:
  extends: .gitleaks-template
include:
  - project: dwp/engineering/pipeline-solutions/gitlab/functions
    ref: 6.0.7
    file:
      - functions/base-mr.gitlab-ci.yml


    include:
  # Builds container image with aws-cli-v2 and jq installed for use in this Component
  - component: $CI_SERVER_FQDN/dwp/engineering/pipeline-solutions/gitlab/components/heroku-site-publish/publish@$CI_COMMIT_SHA
    inputs:
      job_name_suffix: "site"
      app_name: colleague-view


   